"""Export a generated toolpath as a FullControl design.

FullControl (https://fullcontrol.xyz) designs a print as a list of state-change
steps — mostly ``fc.Point`` plus the occasional ``fc.Printer`` / ``fc.Extruder`` /
``fc.ExtrusionGeometry`` object — then ``fc.transform(steps, 'gcode'|'plot', ...)``
turns it into G-code or a Plotly preview.

Because every one of our generators emits through :class:`GcodeWriter`, which now
records each move, we can turn *any* of our shapes (parametric spiral, mesh wrap,
surface-following shell) into a FullControl design. Two outputs:

- :func:`writer_to_fc_script` — a standalone Python script you can paste straight
  into the in-browser editor at fullcontrol.xyz (no install needed) or run locally.
- :func:`writer_to_fc_steps` — builds the actual ``steps`` list if the ``fullcontrol``
  package is importable, so you can ``fc.transform`` it in your own code.

The per-move feedrates we computed (including the Z-velocity and volumetric-flow
clamps) are preserved by emitting ``fc.Printer(print_speed=...)`` whenever the speed
changes — so FullControl honours the same machine-safe limits.
"""
from __future__ import annotations

from .gcode import GcodeWriter


def _compact_moves(writer: GcodeWriter):
    """Yield (x, y, z, feed_mm_min, extruding) for each recorded move."""
    for (x, y, z, extruding, speed) in writer.moves:
        yield (round(x, 4), round(y, 4), round(z, 4),
               round(speed * 60.0, 1), 1 if extruding else 0)


def writer_to_fc_script(
    writer: GcodeWriter,
    *,
    design_name: str = "trident_design",
    travel_speed_mm_s: float | None = None,
    fan_percent: float = 100.0,
    trident_macros: bool = True,
    do_plot: bool = True,
) -> str:
    """Return a standalone FullControl Python script reproducing the toolpath."""
    p = writer.profile
    travel = (travel_speed_mm_s if travel_speed_mm_s is not None else writer.travel_speed) * 60.0
    moves = list(_compact_moves(writer))

    # Build the moves literal compactly (one tuple per line keeps diffs readable).
    moves_lines = ",\n".join(
        f"    ({x}, {y}, {z}, {f}, {e})" for (x, y, z, f, e) in moves
    )

    if trident_macros:
        start_gcode = (
            f"PRINT_START EXTRUDER={writer.nozzle_temp:.0f} "
            f"BED={writer.bed_temp:.0f} MATERIAL={writer.material}"
        )
        # Inject the Trident macros as raw lines (ManualGcode). 'no_primer' skips
        # FullControl's priming line since PRINT_START already purges; 'relative_e'
        # matches PRINT_START's M83.
        init_block = f"""initialization_data={{
        'primer': 'no_primer',
        'print_speed': {writer.print_speed * 60.0:.0f},
        'travel_speed': {travel:.0f},
        'nozzle_temp': {writer.nozzle_temp:.0f},
        'bed_temp': {writer.bed_temp:.0f},
        'relative_e': True,
    }},"""
        start_step = f"steps.append(fc.ManualGcode(text={start_gcode!r}))\n"
        end_step = "steps.append(fc.ManualGcode(text='PRINT_END'))\n"
        extruder_line = "steps.append(fc.Extruder(on=True))"
    else:
        init_block = f"""initialization_data={{
        'print_speed': {writer.print_speed * 60.0:.0f},
        'travel_speed': {travel:.0f},
        'nozzle_temp': {writer.nozzle_temp:.0f},
        'bed_temp': {writer.bed_temp:.0f},
    }},"""
        start_step = ""
        end_step = ""
        extruder_line = "steps.append(fc.Extruder(on=True))"

    return f'''# FullControl design generated by the Trident non-planar G-code tool.
# Paste into the editor at https://fullcontrol.xyz (runs in-browser, no install)
# or run locally after `pip install fullcontrol`.
#
# Shape: {design_name}   moves: {len(moves)}   line_width: {writer.line_width}mm
#        layer_height: {writer.layer_height}mm   bed: {p.bed_size_x}x{p.bed_size_y}mm
import fullcontrol as fc

# (x, y, z, feed_mm_per_min, extruding) — straight from the generator, with the
# Z-velocity and volumetric-flow clamps already baked into the feedrates.
MOVES = [
{moves_lines}
]

steps = []
{start_step}steps.append(fc.ExtrusionGeometry(area_model='rectangle', width={writer.line_width}, height={writer.layer_height}))
steps.append(fc.Printer(travel_speed={travel:.0f}))
steps.append(fc.Fan(speed_percent={fan_percent:.0f}))
{extruder_line}

_on, _feed = 1, None
for x, y, z, feed, e in MOVES:
    if e != _on:
        steps.append(fc.Extruder(on=bool(e))); _on = e
    if e and feed != _feed:
        steps.append(fc.Printer(print_speed=feed)); _feed = feed
    steps.append(fc.Point(x=x, y=y, z=z))
{end_step}

# --- G-code (for the printer) ---
gcode = fc.transform(steps, 'gcode', fc.GcodeControls(
    printer_name='generic',
    {init_block}
    save_as='{design_name}',
))
{"# --- 3D preview (FullControl's Plotly viewer) ---" if do_plot else ""}
{f"fc.transform(steps, 'plot', fc.PlotControls(style='tube', color_type='z_gradient', hide_travel=True))" if do_plot else ""}
'''


def writer_to_fc_steps(writer: GcodeWriter):
    """Build a live FullControl ``steps`` list (requires the fullcontrol package)."""
    try:
        import fullcontrol as fc
    except ImportError as e:  # pragma: no cover - depends on user env
        raise ImportError(
            "The 'fullcontrol' package is not installed. Use writer_to_fc_script() "
            "and paste the result into https://fullcontrol.xyz, or `pip install fullcontrol`."
        ) from e

    steps = [
        fc.ExtrusionGeometry(area_model='rectangle', width=writer.line_width, height=writer.layer_height),
        fc.Printer(travel_speed=writer.travel_speed * 60.0),
        fc.Extruder(on=True),
    ]
    on, feed = 1, None
    for (x, y, z, f, e) in _compact_moves(writer):
        if e != on:
            steps.append(fc.Extruder(on=bool(e))); on = e
        if e and f != feed:
            steps.append(fc.Printer(print_speed=f)); feed = f
        steps.append(fc.Point(x=x, y=y, z=z))
    return steps
